### ISSUE TITLE
RillRate will not register tracers created after a certain duration.

### ISSUE THREAD

**Issue by Blakeinstein** [rillrate/rillrate#5]
Adding even a small delay in adding a tracer, results in the tracer not being registered.
This is replicable by but not limited to adding a delay via Thread::sleep().

* **Version**: RillRate `v0.23.0`
* **Platform**: Replicable on Windows 10 Home.
* **Minimum Reproducible Example**: 
```rust
use std::error::Error;

use std::time::Duration;

fn main() -> Result<(), Box<dyn Error>> {
    let _rillrate = RillRate::from_env("test")?;
    sleep(Duration::from_millis(100));
    let _table = Table::create("test table")?;
    loop {
        continue;
    }
}
```

**Comment by DenisKolodin** [comment]
Thank you for the good report! It really exists. We are fixing it.

**Comment by Blakeinstein** [comment]
Yes this fixes the issue. Thanks.
